import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// SPEC.md §7: workflows generated by `init` must pin `actions/checkout`
// and this repo's own `actions/review` path to exact commit SHAs — never
// a floating tag or branch. Those SHAs are release-time facts (the
// checkout action's latest verified release, and the commit this package
// version was cut from), not something to guess at generation time.

export interface PinnedShas {
  checkoutSha: string;
  reviewActionSha: string;
}

export class UnpinnedReleaseError extends Error {
  constructor(missing: string) {
    super(
      `pinned-shas.json is missing "${missing}". This package build is not release-ready — ` +
        "the release process must populate exact commit SHAs before `init` can write a workflow.",
    );
    this.name = "UnpinnedReleaseError";
  }
}

const __dirname = dirname(fileURLToPath(import.meta.url));

export function loadPinnedShas(pathOverride?: string): PinnedShas {
  const path = pathOverride ?? join(__dirname, "..", "..", "pinned-shas.json");
  const raw = JSON.parse(readFileSync(path, "utf8")) as Partial<PinnedShas>;
  if (!raw.checkoutSha) throw new UnpinnedReleaseError("checkoutSha");
  if (!raw.reviewActionSha) throw new UnpinnedReleaseError("reviewActionSha");
  return { checkoutSha: raw.checkoutSha, reviewActionSha: raw.reviewActionSha };
}
