import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// SPEC.md §7: workflows generated by `init` must pin `actions/checkout`
// and THIS PACKAGE'S OWN `actions/review` path to exact commit SHAs —
// never a floating tag or branch. `actionOwner`/`actionRepo` identify
// where actions/review actually lives (this package's public repo) —
// they are NOT the repo `init` is installing into, which is a different
// repo determined at runtime from the target's git remote. Conflating
// the two was a real bug: it generated `uses: <target-owner>/<target-repo>/
// actions/review@sha`, which GitHub Actions can never resolve.

export interface PinnedShas {
  checkoutSha: string;
  reviewActionSha: string;
  actionOwner: string;
  actionRepo: string;
  // actions/cache pin for the CLI-install cache (SPEC.md §7, shipped
  // 1.1.0): avoids a fresh npm fetch on every PR for auth: subscription.
  cacheSha: string;
}

export class UnpinnedReleaseError extends Error {
  constructor(missing: string) {
    super(
      `pinned-shas.json is missing "${missing}". This package build is not release-ready — ` +
        "the release process must populate exact commit SHAs before `init` can write a workflow.",
    );
    this.name = "UnpinnedReleaseError";
  }
}

const __dirname = dirname(fileURLToPath(import.meta.url));

export function loadPinnedShas(pathOverride?: string): PinnedShas {
  const path = pathOverride ?? join(__dirname, "..", "..", "pinned-shas.json");
  const raw = JSON.parse(readFileSync(path, "utf8")) as Partial<PinnedShas>;
  if (!raw.checkoutSha) throw new UnpinnedReleaseError("checkoutSha");
  if (!raw.reviewActionSha) throw new UnpinnedReleaseError("reviewActionSha");
  if (!raw.actionOwner) throw new UnpinnedReleaseError("actionOwner");
  if (!raw.actionRepo) throw new UnpinnedReleaseError("actionRepo");
  if (!raw.cacheSha) throw new UnpinnedReleaseError("cacheSha");
  return {
    checkoutSha: raw.checkoutSha,
    reviewActionSha: raw.reviewActionSha,
    actionOwner: raw.actionOwner,
    actionRepo: raw.actionRepo,
    cacheSha: raw.cacheSha,
  };
}
